<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<testsuite errors="0" failures="2" name="io.cucumber.core.plugin.JUnitFormatter" skipped="0" tests="2" time="33.429">
<testcase classname="Perform functional testing around the actual contents of the reports that the service generates." name="Submitting get request for dr_d1 json formatted end point and validating expected output data is matching with actual data for a scenario:dr_d1_sc_json.json" time="2.205">
<failure message="Bad response code: 500" type="com.elsevier.usage.apitests.exception.UnexpectedStatusCodeException"><![CDATA[Given I select the environment on which the execution is to be processed....passed
And I submit a get request with the required request parameters such as s000000004,counter,2016-01-01,2016-12-31,sc and json.passed
And I provide the service url dr_d1 and wait until response is 200 with "retry_limit".failed
Then I compare the actual output sent by service with expected output file present in expected-content directory "src/test/expected-content/dr_d1_sc_json.json"..skipped

StackTrace:
com.elsevier.usage.apitests.exception.UnexpectedStatusCodeException: Bad response code: 500
	at com.elsevier.usage.apitests.stepdefinitions.MyStepdefs.isExpectedResponseCode(MyStepdefs.java:62)
	at com.elsevier.usage.apitests.stepdefinitions.MyStepdefs.serviceURLandLimit(MyStepdefs.java:51)
	at ✽.I provide the service url dr_d1 and wait until response is 200 with "retry_limit"(file:///Users/sistum/usage-projects/restassuredpractice/src/test/java/com/elsevier/usage/apitests/features/getreport.feature:7)
]]></failure>
</testcase>
<testcase classname="Perform functional testing around the actual contents of the reports that the service generates." name="Submitting get request for dr_d1 json formatted end point and validating expected output data is matching with actual data for a scenario:dr_d1_sc_json.json 2" time="31.069">
<failure message="Condition with lambda expression in com.elsevier.usage.apitests.stepdefinitions.MyStepdefs was not fulfilled within 30 seconds." type="org.awaitility.core.ConditionTimeoutException"><![CDATA[Given I select the environment on which the execution is to be processed....passed
And I submit a get request with the required request parameters such as s000000002,counter,2016-01-01,2016-12-31,sc and json.passed
And I provide the service url dr_d1 and wait until response is 200 with "retry_limit".failed
Then I compare the actual output sent by service with expected output file present in expected-content directory "src/test/expected-content/dr_d1_sc_json.json"..skipped

StackTrace:
org.awaitility.core.ConditionTimeoutException: Condition with lambda expression in com.elsevier.usage.apitests.stepdefinitions.MyStepdefs was not fulfilled within 30 seconds.
	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:136)
	at org.awaitility.core.CallableCondition.await(CallableCondition.java:79)
	at org.awaitility.core.CallableCondition.await(CallableCondition.java:27)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:840)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:802)
	at com.elsevier.usage.apitests.stepdefinitions.MyStepdefs.serviceURLandLimit(MyStepdefs.java:53)
	at ✽.I provide the service url dr_d1 and wait until response is 200 with "retry_limit"(file:///Users/sistum/usage-projects/restassuredpractice/src/test/java/com/elsevier/usage/apitests/features/getreport.feature:7)
]]></failure>
</testcase>
</testsuite>
